include:
  - CHANGELOG.md
  - CONTRIBUTING.md
title: skuba

remote_theme: pmarsceill/just-the-docs

aux_links:
  GitHub:
    - https://github.com/seek-oss/skuba
  npm:
    - https://www.npmjs.com/package/skuba
aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: Edit this page
gh_edit_repository: https://github.com/seek-oss/skuba
gh_edit_branch: master
gh_edit_view_mode: tree
